//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewWaghralkar.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice
    {
        public long Invoice__ID { get; set; }
        public System.DateTime Date { get; set; }
        public decimal Amount { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public Nullable<decimal> Delivery { get; set; }
        public string Status { get; set; }
        public string Cust_Id { get; set; }
    }
}
