//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewWaghralkar.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Issue_Master
    {
        public long Issue_ID { get; set; }
        public long Module_ID { get; set; }
        public string Issue_Details { get; set; }
        public decimal Visite_Charge { get; set; }
        public string Data1 { get; set; }
        public string Status { get; set; }
    }
}
