//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewWaghralkar.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemData
    {
        public long Item_ID { get; set; }
        public int Main_Category { get; set; }
        public int Sub_Category1 { get; set; }
        public int Sub_Category2 { get; set; }
        public Nullable<int> Sub_Category3 { get; set; }
        public int Type { get; set; }
        public int Brand { get; set; }
        public int Size { get; set; }
        public string Name { get; set; }
        public decimal P_Price { get; set; }
        public decimal S_Price { get; set; }
        public decimal Discount { get; set; }
        public Nullable<decimal> Tax { get; set; }
        public string Specification { get; set; }
        public decimal Qty { get; set; }
        public int Pack { get; set; }
        public int Unit { get; set; }
        public string Start_Date { get; set; }
        public string Data1 { get; set; }
        public string Data2 { get; set; }
        public string Data3 { get; set; }
        public string Data4 { get; set; }
        public string Data5 { get; set; }
        public string Data6 { get; set; }
        public string Status { get; set; }
        public string Photo { get; set; }
        public string Data7 { get; set; }
        public string Data8 { get; set; }
        public string Data9 { get; set; }
        public string Data10 { get; set; }
        public string Data11 { get; set; }
        public string Data12 { get; set; }
        public string Data13 { get; set; }
        public string Data14 { get; set; }
    }
}
