//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewWaghralkar.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WaghralkarEntities : DbContext
    {
        public WaghralkarEntities()
            : base("name=WaghralkarEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Activity> Activities { get; set; }
        public virtual DbSet<admin> admins { get; set; }
        public virtual DbSet<Award> Awards { get; set; }
        public virtual DbSet<Blog> Blogs { get; set; }
        public virtual DbSet<Brand_Master> Brand_Master { get; set; }
        public virtual DbSet<Invoice> Invoices { get; set; }
        public virtual DbSet<ItemData> ItemDatas { get; set; }
        public virtual DbSet<MainCategory> MainCategories { get; set; }
        public virtual DbSet<mytable> mytables { get; set; }
        public virtual DbSet<Photogallary> Photogallaries { get; set; }
        public virtual DbSet<Region_Master> Region_Master { get; set; }
        public virtual DbSet<Registration> Registrations { get; set; }
        public virtual DbSet<Size_Master> Size_Master { get; set; }
        public virtual DbSet<Sub_Category1> Sub_Category1 { get; set; }
        public virtual DbSet<Sub_Category2> Sub_Category2 { get; set; }
        public virtual DbSet<Sub_Category3> Sub_Category3 { get; set; }
        public virtual DbSet<Tax_Master> Tax_Master { get; set; }
        public virtual DbSet<Type_Master> Type_Master { get; set; }
        public virtual DbSet<Unit_Master> Unit_Master { get; set; }
        public virtual DbSet<Videogallery> Videogalleries { get; set; }
        public virtual DbSet<Cart> Carts { get; set; }
        public virtual DbSet<Delivery> Deliveries { get; set; }
        public virtual DbSet<Issue_Master> Issue_Master { get; set; }
        public virtual DbSet<Order1> Order1 { get; set; }
        public virtual DbSet<Sitem_Master> Sitem_Master { get; set; }
        public virtual DbSet<SpecialOffer> SpecialOffers { get; set; }
    }
}
