//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewWaghralkar.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order1
    {
        public long CartId { get; set; }
        public long Invoice_Id { get; set; }
        public long Item_ID { get; set; }
        public System.DateTime Date { get; set; }
        public string Status { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public Nullable<decimal> Qty { get; set; }
        public Nullable<decimal> Tax { get; set; }
    }
}
