//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewWaghralkar.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sitem_Master
    {
        public long Sitem_ID { get; set; }
        public long Module_ID { get; set; }
        public string Sitem_Details { get; set; }
        public decimal Sitem_Pprice { get; set; }
        public decimal Sitem_Sprice { get; set; }
        public decimal Sitem_Margin { get; set; }
        public decimal Sitem_service_Amt { get; set; }
        public string Data1 { get; set; }
        public string Status { get; set; }
    }
}
