//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewWaghralkar.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SpecialOffer
    {
        public long Offer_ID { get; set; }
        public long Item_ID { get; set; }
        public string Offer_Details { get; set; }
        public decimal Offer_Percentage { get; set; }
        public System.DateTime Offer_Date { get; set; }
        public string Offer_Type { get; set; }
        public string Status { get; set; }
        public string Photo { get; set; }
    }
}
